version: '2.2'

services:

  # elkstack
  elkstack:
    container_name: elkstack
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"

  # splunk
  splunk:
    container_name: splunk
    image: splunk/splunk
    ports:
      - "8000:8000"
      - "8088:8088"
    environment:
      SPLUNK_PASSWORD: "ThisIsMyMagicPassword"
      SPLUNK_START_ARGS: "--accept-license"
    volumes:
      - "/home/vagrant/git/vagrant-ubuntu-docker-host/files/dashboards:/tmp/dashboards"

  # mongodb
  mongodb:
    container_name: mongodb
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  # elasticsearch
  elasticsearch:
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
      - "/home/vagrant/git/vagrant-ubuntu-docker-host/files/dashboards:/tmp/dashboards"
    restart: "on-failure"

# volumes    
volumes:
  mongodb_data:
  es_data:
  graylog_data:
  graylog_journal: