services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  #DB in share for persistence
    volumes:
       - /video/graylog/mongodb:/data/db
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    #data folder in share for persistence
    volumes:
      - /video/graylog/elasticsearchdata:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - node.max_local_storage_nodes=4
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:<version>
    #journal and config directories in local NFS share for persistence
    volumes:
       - /video/graylog/journal:/usr/share/graylog/data/journal
       - /video/graylog/config:/usr/share/graylog/data/config
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=MySuperSecureAdminPassword
      # Password: MySuperSecureAdminPassword
      - GRAYLOG_ROOT_PASSWORD_SHA2=3c62d0c0dda7c88cf9163f06661c9dba97c9f95100346d992645bcc1a6821eb6
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:7555
      - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:7555/
      #- GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://0.0.0.0:7555
      #- GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=smtp.example.com
      #- GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
      #- GRAYLOG_TRANSPORT_EMAIL_PORT=25
      #- GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=false
      #- GRAYLOG_TRANSPORT_EMAIL_USE_TLS=false
      #- GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
      #- GRAYLOG_TRANSPORT_FROM_EMAIL=youremail@yourdomain.com
      #- GRAYLOG_TRANSPORT_SUBJECT_PREFIX=[graylog]
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 7555:7555 # Graylog web interface and REST API      
      - 8514:8514 # Syslog TCP
      - 8514:8514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP