version: '2.2'

services:

  # elkstack
  elkstack:
    container_name: elkstack
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"

  # splunk
  splunk:
    container_name: splunk
    image: splunk/splunk
    ports:
      - "8000:8000"
      - "8088:8088"
    environment:
      SPLUNK_PASSWORD: "ThisIsMyMagicPassword"
      SPLUNK_START_ARGS: "--accept-license"
      